version: "3"

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9090:9000"
    networks:
      - sonarnet
    # environment:
    #   - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

networks:
  sonarnet:
